[pytest]
markers =
    system: marks tests as system tests (run time consuming)
    smoke: marks tests as smoke tests
    integration: marks tests as integration tests
    unit: marks tests as unit tests
